---
- hosts: methanika-hosts
  become: yes
  vars:
    install_path: "/opt/livemon"
  tasks:
  - name: Install docker repo
    apt_repository:
     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
